version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - /home/nguyenbanh/kafka-installation/persistence/zookeeper:/bitnami/zookeeper

  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=500
    volumes:
      - /home/nguyenbanh/kafka-installation/persistence/kafka/500:/bitnami/kafka
    depends_on:
      - zookeeper
